// ─── App Theme System ─────────────────────────────────────────────────────────

export interface AppTheme {
  name: string;
  primary: string;
  secondary: string;
  accent: string;
  bg: string;
  bgCard: string;
  border: string;
  textMuted: string;
}

export const DEFAULT_THEME: AppTheme = {
  name: "Default Purple",
  primary: "#7c3aed",
  secondary: "#4f46e5",
  accent: "#a78bfa",
  bg: "#030712",
  bgCard: "rgba(255,255,255,0.05)",
  border: "rgba(255,255,255,0.10)",
  textMuted: "rgba(255,255,255,0.40)",
};

const THEME_KEY = "gamesched_theme_v1";

export function loadTheme(): AppTheme {
  try {
    const stored = localStorage.getItem(THEME_KEY);
    return stored ? JSON.parse(stored) : DEFAULT_THEME;
  } catch {
    return DEFAULT_THEME;
  }
}

export function saveTheme(t: AppTheme) {
  localStorage.setItem(THEME_KEY, JSON.stringify(t));
}

function hexToRgb(hex: string): [number, number, number] {
  const c = hex.replace("#", "");
  return [parseInt(c.slice(0,2),16), parseInt(c.slice(2,4),16), parseInt(c.slice(4,6),16)];
}

export function applyTheme(t: AppTheme) {
  // Set CSS variables
  const s = document.documentElement.style;
  s.setProperty("--color-primary",   t.primary);
  s.setProperty("--color-secondary", t.secondary);
  s.setProperty("--color-accent",    t.accent);
  s.setProperty("--color-bg",        t.bg);
  s.setProperty("--color-card",      t.bgCard);
  s.setProperty("--color-border",    t.border);
  s.setProperty("--color-muted",     t.textMuted);

  // Inject dynamic <style> that overrides all hardcoded Tailwind purple/indigo
  // so every component in the app responds to theme changes immediately.
  const id = "theme-override-style";
  let el = document.getElementById(id) as HTMLStyleElement | null;
  if (!el) {
    el = document.createElement("style");
    el.id = id;
    document.head.appendChild(el);
  }

  const [pr, pg, pb] = hexToRgb(t.primary);
  const [sr, sg, sb] = hexToRgb(t.secondary);
  

  el.textContent = `
    /* Dynamic theme override — generated by applyTheme() */

    /* ── Gradient buttons (Add Task, Submit, Done button) ── */
    .bg-gradient-to-r.from-purple-600.to-indigo-600 {
      background: linear-gradient(135deg, ${t.primary}, ${t.secondary}) !important;
    }
    /* Brain icon gradient */
    .bg-gradient-to-br.from-purple-500.to-indigo-600 {
      background: linear-gradient(135deg, ${t.primary}, ${t.secondary}) !important;
    }

    /* ── Solid primary color ── */
    .bg-purple-600 { background-color: ${t.primary} !important; }
    .hover\\:bg-purple-600:hover { background-color: ${t.primary} !important; }

    /* ── Text colors ── */
    .text-purple-400 { color: ${t.accent} !important; }
    .text-purple-300 { color: ${t.accent}bb !important; }

    /* ── Gradient stops ── */
    .from-purple-500, .from-purple-600 { --tw-gradient-from: ${t.primary} !important; }
    .to-indigo-600   { --tw-gradient-to:   ${t.secondary} !important; }

    .from-purple-600\\/20 { --tw-gradient-from: rgba(${pr},${pg},${pb},0.20) !important; }
    .from-purple-600\\/30 { --tw-gradient-from: rgba(${pr},${pg},${pb},0.30) !important; }
    .to-indigo-600\\/20   { --tw-gradient-to:   rgba(${sr},${sg},${sb},0.20) !important; }
    .to-indigo-600\\/30   { --tw-gradient-to:   rgba(${sr},${sg},${sb},0.30) !important; }

    /* ── Transparent fills ── */
    .bg-purple-500\\/10, .bg-purple-600\\/10 { background-color: rgba(${pr},${pg},${pb},0.10) !important; }
    .bg-purple-600\\/20 { background-color: rgba(${pr},${pg},${pb},0.20) !important; }
    .bg-purple-600\\/90 { background-color: rgba(${pr},${pg},${pb},0.90) !important; }
    .bg-indigo-500\\/10 { background-color: rgba(${sr},${sg},${sb},0.10) !important; }

    /* ── Borders ── */
    .border-purple-500 { border-color: ${t.primary} !important; }
    .border-purple-500\\/30 { border-color: rgba(${pr},${pg},${pb},0.30) !important; }
    .border-purple-500\\/40 { border-color: rgba(${pr},${pg},${pb},0.40) !important; }
    .border-purple-500\\/60 { border-color: rgba(${pr},${pg},${pb},0.60) !important; }
    .hover\\:border-purple-500\\/60:hover { border-color: rgba(${pr},${pg},${pb},0.60) !important; }

    /* ── Focus ── */
    .focus\\:border-purple-500:focus { border-color: ${t.primary} !important; }
    .focus\\:bg-purple-500\\/10:focus { background-color: rgba(${pr},${pg},${pb},0.10) !important; }
    input:focus, select:focus {
      border-color: ${t.primary} !important;
      outline-color: ${t.primary} !important;
    }

    /* ── Glow / shadow ── */
    .theme-glow {
      box-shadow: 0 0 20px rgba(${pr},${pg},${pb},0.35) !important;
    }
    .shadow-purple-500\\/30,
    .shadow-lg.shadow-purple-500\\/30 {
      box-shadow: 0 10px 15px -3px rgba(${pr},${pg},${pb},0.30) !important;
    }

    /* ── Ring ── */
    .ring-2.ring-purple-500 { --tw-ring-color: ${t.primary} !important; }

    /* ── Calendar day count badge ── */
    .bg-purple-600.rounded-full { background-color: ${t.primary} !important; }

    /* ── Accent uses in header stat cards ── */
    .text-\\[var\\(--color-accent\\)\\] { color: ${t.accent} !important; }
  `;
}